export const TYPE_DIRECTORY = 'TYPE_DIRECTORY'
export const TYPE_FILE = 'TYPE_FILE'
export const TYPE_UNKNOWN = 'TYPE_UNKNOWN'
export const TYPE_GROUP = 'TYPE_GROUP'
export const TYPE_FIRST = 'TYPE_FIRST'